// -------------------------------------------------------------
// 
// File Name: hdlsrc\gm_hdlcoder_commviterbi\ACSEngine.v
// Created: 2024-06-18 17:16:01
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ACSEngine
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/ACS/ACSEngine
// Hierarchy Level: 3
// Model version: 10.6
// 
// Instantiate the ACS units
// Pass the right state metric and branch metrics to each instance
// Gather the output of each instance to send as output
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ACSEngine
          (branchMetric_0,
           branchMetric_1,
           branchMetric_2,
           branchMetric_3,
           stateMetric_0,
           stateMetric_1,
           stateMetric_2,
           stateMetric_3,
           stateMetric_4,
           stateMetric_5,
           stateMetric_6,
           stateMetric_7,
           acsDecision_0,
           acsDecision_1,
           acsDecision_2,
           acsDecision_3,
           acsDecision_4,
           acsDecision_5,
           acsDecision_6,
           acsDecision_7,
           nextStateMetric_0,
           nextStateMetric_1,
           nextStateMetric_2,
           nextStateMetric_3,
           nextStateMetric_4,
           nextStateMetric_5,
           nextStateMetric_6,
           nextStateMetric_7);


  input   [4:0] branchMetric_0;  // ufix5
  input   [4:0] branchMetric_1;  // ufix5
  input   [4:0] branchMetric_2;  // ufix5
  input   [4:0] branchMetric_3;  // ufix5
  input   [4:0] stateMetric_0;  // ufix5
  input   [4:0] stateMetric_1;  // ufix5
  input   [4:0] stateMetric_2;  // ufix5
  input   [4:0] stateMetric_3;  // ufix5
  input   [4:0] stateMetric_4;  // ufix5
  input   [4:0] stateMetric_5;  // ufix5
  input   [4:0] stateMetric_6;  // ufix5
  input   [4:0] stateMetric_7;  // ufix5
  output  acsDecision_0;  // ufix1
  output  acsDecision_1;  // ufix1
  output  acsDecision_2;  // ufix1
  output  acsDecision_3;  // ufix1
  output  acsDecision_4;  // ufix1
  output  acsDecision_5;  // ufix1
  output  acsDecision_6;  // ufix1
  output  acsDecision_7;  // ufix1
  output  [4:0] nextStateMetric_0;  // ufix5
  output  [4:0] nextStateMetric_1;  // ufix5
  output  [4:0] nextStateMetric_2;  // ufix5
  output  [4:0] nextStateMetric_3;  // ufix5
  output  [4:0] nextStateMetric_4;  // ufix5
  output  [4:0] nextStateMetric_5;  // ufix5
  output  [4:0] nextStateMetric_6;  // ufix5
  output  [4:0] nextStateMetric_7;  // ufix5


  wire acsdec_entry0;  // ufix1
  wire [4:0] nstMet_entry0;  // ufix5
  wire acsdec_entry1;  // ufix1
  wire [4:0] nstMet_entry1;  // ufix5
  wire acsdec_entry2;  // ufix1
  wire [4:0] nstMet_entry2;  // ufix5
  wire acsdec_entry3;  // ufix1
  wire [4:0] nstMet_entry3;  // ufix5
  wire acsdec_entry4;  // ufix1
  wire [4:0] nstMet_entry4;  // ufix5
  wire acsdec_entry5;  // ufix1
  wire [4:0] nstMet_entry5;  // ufix5
  wire acsdec_entry6;  // ufix1
  wire [4:0] nstMet_entry6;  // ufix5
  wire acsdec_entry7;  // ufix1
  wire [4:0] nstMet_entry7;  // ufix5


  // ACSUnit1
  ACSUnit u_ACSUnit1 (.bmet0(branchMetric_0),  // ufix5
                      .bmet1(branchMetric_1),  // ufix5
                      .smet0(stateMetric_0),  // ufix5
                      .smet1(stateMetric_1),  // ufix5
                      .branchdec(acsdec_entry0),  // ufix1
                      .nextsmet(nstMet_entry0)  // ufix5
                      );

  assign acsDecision_0 = acsdec_entry0;

  // ACSUnit2
  ACSUnit u_ACSUnit2 (.bmet0(branchMetric_2),  // ufix5
                      .bmet1(branchMetric_3),  // ufix5
                      .smet0(stateMetric_2),  // ufix5
                      .smet1(stateMetric_3),  // ufix5
                      .branchdec(acsdec_entry1),  // ufix1
                      .nextsmet(nstMet_entry1)  // ufix5
                      );

  assign acsDecision_1 = acsdec_entry1;

  // ACSUnit3
  ACSUnit u_ACSUnit3 (.bmet0(branchMetric_1),  // ufix5
                      .bmet1(branchMetric_0),  // ufix5
                      .smet0(stateMetric_4),  // ufix5
                      .smet1(stateMetric_5),  // ufix5
                      .branchdec(acsdec_entry2),  // ufix1
                      .nextsmet(nstMet_entry2)  // ufix5
                      );

  assign acsDecision_2 = acsdec_entry2;

  // ACSUnit4
  ACSUnit u_ACSUnit4 (.bmet0(branchMetric_3),  // ufix5
                      .bmet1(branchMetric_2),  // ufix5
                      .smet0(stateMetric_6),  // ufix5
                      .smet1(stateMetric_7),  // ufix5
                      .branchdec(acsdec_entry3),  // ufix1
                      .nextsmet(nstMet_entry3)  // ufix5
                      );

  assign acsDecision_3 = acsdec_entry3;

  // ACSUnit5
  ACSUnit u_ACSUnit5 (.bmet0(branchMetric_3),  // ufix5
                      .bmet1(branchMetric_2),  // ufix5
                      .smet0(stateMetric_0),  // ufix5
                      .smet1(stateMetric_1),  // ufix5
                      .branchdec(acsdec_entry4),  // ufix1
                      .nextsmet(nstMet_entry4)  // ufix5
                      );

  assign acsDecision_4 = acsdec_entry4;

  // ACSUnit6
  ACSUnit u_ACSUnit6 (.bmet0(branchMetric_1),  // ufix5
                      .bmet1(branchMetric_0),  // ufix5
                      .smet0(stateMetric_2),  // ufix5
                      .smet1(stateMetric_3),  // ufix5
                      .branchdec(acsdec_entry5),  // ufix1
                      .nextsmet(nstMet_entry5)  // ufix5
                      );

  assign acsDecision_5 = acsdec_entry5;

  // ACSUnit7
  ACSUnit u_ACSUnit7 (.bmet0(branchMetric_2),  // ufix5
                      .bmet1(branchMetric_3),  // ufix5
                      .smet0(stateMetric_4),  // ufix5
                      .smet1(stateMetric_5),  // ufix5
                      .branchdec(acsdec_entry6),  // ufix1
                      .nextsmet(nstMet_entry6)  // ufix5
                      );

  assign acsDecision_6 = acsdec_entry6;

  // ACSUnit8
  ACSUnit u_ACSUnit8 (.bmet0(branchMetric_0),  // ufix5
                      .bmet1(branchMetric_1),  // ufix5
                      .smet0(stateMetric_6),  // ufix5
                      .smet1(stateMetric_7),  // ufix5
                      .branchdec(acsdec_entry7),  // ufix1
                      .nextsmet(nstMet_entry7)  // ufix5
                      );

  assign acsDecision_7 = acsdec_entry7;

  assign nextStateMetric_0 = nstMet_entry0;

  assign nextStateMetric_1 = nstMet_entry1;

  assign nextStateMetric_2 = nstMet_entry2;

  assign nextStateMetric_3 = nstMet_entry3;

  assign nextStateMetric_4 = nstMet_entry4;

  assign nextStateMetric_5 = nstMet_entry5;

  assign nextStateMetric_6 = nstMet_entry6;

  assign nextStateMetric_7 = nstMet_entry7;

endmodule  // ACSEngine

