// -------------------------------------------------------------
// 
// File Name: hdlsrc\gm_hdlcoder_commviterbi\ACSUnit.v
// Created: 2024-06-18 17:16:01
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ACSUnit
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/ACS/ACSEngine/ACSUnit
// Hierarchy Level: 4
// Model version: 10.6
// 
// Add Compare Select Unit
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ACSUnit
          (bmet0,
           bmet1,
           smet0,
           smet1,
           branchdec,
           nextsmet);


  input   [4:0] bmet0;  // ufix5
  input   [4:0] bmet1;  // ufix5
  input   [4:0] smet0;  // ufix5
  input   [4:0] smet1;  // ufix5
  output  branchdec;  // ufix1
  output  [4:0] nextsmet;  // ufix5


  wire [4:0] sum0;  // ufix5
  wire [4:0] sum1;  // ufix5
  wire relop_relop1;


  // Add branch metric and state metric
  assign sum0 = bmet0 + smet0;



  // Add branch metric and state metric
  assign sum1 = bmet1 + smet1;



  // Compare
  assign relop_relop1 = sum0 > sum1;



  assign branchdec = relop_relop1;

  // Select
  assign nextsmet = (relop_relop1 == 1'b0 ? sum0 :
              sum1);



endmodule  // ACSUnit

