// -------------------------------------------------------------
// 
// File Name: hdlsrc\gm_hdlcoder_commviterbi\BranchMetric.v
// Created: 2024-06-18 17:16:01
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BranchMetric
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/BranchMetric
// Hierarchy Level: 2
// Model version: 10.6
// 
// Branch Metric Computation
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BranchMetric
          (din_0,
           din_1,
           bMet_0,
           bMet_1,
           bMet_2,
           bMet_3);


  input   din_0;  // boolean
  input   din_1;  // boolean
  output  [1:0] bMet_0;  // ufix2
  output  [1:0] bMet_1;  // ufix2
  output  [1:0] bMet_2;  // ufix2
  output  [1:0] bMet_3;  // ufix2


  wire [1:0] BMet_adders_1;  // ufix2
  wire [1:0] BMet_adders_2;  // ufix2
  wire [1:0] bMet_entry1;  // ufix2
  wire nsDecmax;
  wire maxsubin2;
  wire [1:0] BMet_adders_4;  // ufix2
  wire [1:0] BMet_adders_5;  // ufix2
  wire [1:0] bMet_entry2;  // ufix2
  wire maxsubin1;
  wire [1:0] BMet_adders_7;  // ufix2
  wire [1:0] BMet_adders_8;  // ufix2
  wire [1:0] bMet_entry3;  // ufix2
  wire [1:0] BMet_adders_10;  // ufix2
  wire [1:0] BMet_adders_11;  // ufix2
  wire [1:0] bMet_entry4;  // ufix2


  assign BMet_adders_1 = {1'b0, din_1};
  assign BMet_adders_2 = {1'b0, din_0};
  assign bMet_entry1 = BMet_adders_1 + BMet_adders_2;



  assign bMet_0 = bMet_entry1;

  // Max value of nsDec data type
  assign nsDecmax = 1'b1;



  assign maxsubin2 = nsDecmax ^ din_1;



  assign BMet_adders_4 = {1'b0, maxsubin2};
  assign BMet_adders_5 = {1'b0, din_0};
  assign bMet_entry2 = BMet_adders_4 + BMet_adders_5;



  assign bMet_1 = bMet_entry2;

  assign maxsubin1 = nsDecmax ^ din_0;



  assign BMet_adders_7 = {1'b0, din_1};
  assign BMet_adders_8 = {1'b0, maxsubin1};
  assign bMet_entry3 = BMet_adders_7 + BMet_adders_8;



  assign bMet_2 = bMet_entry3;

  assign BMet_adders_10 = {1'b0, maxsubin2};
  assign BMet_adders_11 = {1'b0, maxsubin1};
  assign bMet_entry4 = BMet_adders_10 + BMet_adders_11;



  assign bMet_3 = bMet_entry4;

endmodule  // BranchMetric

