// -------------------------------------------------------------
// 
// File Name: hdlsrc\gm_hdlcoder_commviterbi\Traceback.v
// Created: 2024-06-18 17:16:01
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Traceback
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/Traceback
// Hierarchy Level: 2
// Model version: 10.6
// 
// Traceback Decoding
// Connects traceback units and adds 4 pipeline registers
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Traceback
          (clk,
           reset,
           enb,
           dec_0,
           dec_1,
           dec_2,
           dec_3,
           dec_4,
           dec_5,
           dec_6,
           dec_7,
           idx,
           decoded);


  input   clk;
  input   reset;
  input   enb;
  input   dec_0;  // ufix1
  input   dec_1;  // ufix1
  input   dec_2;  // ufix1
  input   dec_3;  // ufix1
  input   dec_4;  // ufix1
  input   dec_5;  // ufix1
  input   dec_6;  // ufix1
  input   dec_7;  // ufix1
  input   [2:0] idx;  // ufix3
  output  decoded;  // ufix1


  wire dec1_0;  // ufix1
  wire dec1_1;  // ufix1
  wire dec1_2;  // ufix1
  wire dec1_3;  // ufix1
  wire dec1_4;  // ufix1
  wire dec1_5;  // ufix1
  wire dec1_6;  // ufix1
  wire dec1_7;  // ufix1
  wire [2:0] idx1;  // ufix3
  wire dec2_0;  // ufix1
  wire dec2_1;  // ufix1
  wire dec2_2;  // ufix1
  wire dec2_3;  // ufix1
  wire dec2_4;  // ufix1
  wire dec2_5;  // ufix1
  wire dec2_6;  // ufix1
  wire dec2_7;  // ufix1
  wire [2:0] idx2;  // ufix3
  wire dec3_0;  // ufix1
  wire dec3_1;  // ufix1
  wire dec3_2;  // ufix1
  wire dec3_3;  // ufix1
  wire dec3_4;  // ufix1
  wire dec3_5;  // ufix1
  wire dec3_6;  // ufix1
  wire dec3_7;  // ufix1
  wire [2:0] idx3;  // ufix3
  wire dec4_0;  // ufix1
  wire dec4_1;  // ufix1
  wire dec4_2;  // ufix1
  wire dec4_3;  // ufix1
  wire dec4_4;  // ufix1
  wire dec4_5;  // ufix1
  wire dec4_6;  // ufix1
  wire dec4_7;  // ufix1
  wire [2:0] idx4;  // ufix3
  wire [7:0] dec4;  // ufix1 [8]
  reg  [7:0] decpipereg1;  // ufix1 [8]
  reg [2:0] idxpipereg1;  // ufix3
  wire dec5_0;  // ufix1
  wire dec5_1;  // ufix1
  wire dec5_2;  // ufix1
  wire dec5_3;  // ufix1
  wire dec5_4;  // ufix1
  wire dec5_5;  // ufix1
  wire dec5_6;  // ufix1
  wire dec5_7;  // ufix1
  wire [2:0] idx5;  // ufix3
  wire dec6_0;  // ufix1
  wire dec6_1;  // ufix1
  wire dec6_2;  // ufix1
  wire dec6_3;  // ufix1
  wire dec6_4;  // ufix1
  wire dec6_5;  // ufix1
  wire dec6_6;  // ufix1
  wire dec6_7;  // ufix1
  wire [2:0] idx6;  // ufix3
  wire dec7_0;  // ufix1
  wire dec7_1;  // ufix1
  wire dec7_2;  // ufix1
  wire dec7_3;  // ufix1
  wire dec7_4;  // ufix1
  wire dec7_5;  // ufix1
  wire dec7_6;  // ufix1
  wire dec7_7;  // ufix1
  wire [2:0] idx7;  // ufix3
  wire dec8_0;  // ufix1
  wire dec8_1;  // ufix1
  wire dec8_2;  // ufix1
  wire dec8_3;  // ufix1
  wire dec8_4;  // ufix1
  wire dec8_5;  // ufix1
  wire dec8_6;  // ufix1
  wire dec8_7;  // ufix1
  wire [2:0] idx8;  // ufix3
  wire [7:0] dec8;  // ufix1 [8]
  reg  [7:0] decpipereg2;  // ufix1 [8]
  reg [2:0] idxpipereg2;  // ufix3
  wire dec9_0;  // ufix1
  wire dec9_1;  // ufix1
  wire dec9_2;  // ufix1
  wire dec9_3;  // ufix1
  wire dec9_4;  // ufix1
  wire dec9_5;  // ufix1
  wire dec9_6;  // ufix1
  wire dec9_7;  // ufix1
  wire [2:0] idx9;  // ufix3
  wire dec10_0;  // ufix1
  wire dec10_1;  // ufix1
  wire dec10_2;  // ufix1
  wire dec10_3;  // ufix1
  wire dec10_4;  // ufix1
  wire dec10_5;  // ufix1
  wire dec10_6;  // ufix1
  wire dec10_7;  // ufix1
  wire [2:0] idx10;  // ufix3
  wire dec11_0;  // ufix1
  wire dec11_1;  // ufix1
  wire dec11_2;  // ufix1
  wire dec11_3;  // ufix1
  wire dec11_4;  // ufix1
  wire dec11_5;  // ufix1
  wire dec11_6;  // ufix1
  wire dec11_7;  // ufix1
  wire [2:0] idx11;  // ufix3
  wire dec12_0;  // ufix1
  wire dec12_1;  // ufix1
  wire dec12_2;  // ufix1
  wire dec12_3;  // ufix1
  wire dec12_4;  // ufix1
  wire dec12_5;  // ufix1
  wire dec12_6;  // ufix1
  wire dec12_7;  // ufix1
  wire [2:0] idx12;  // ufix3
  wire [7:0] dec12;  // ufix1 [8]
  reg  [7:0] decpipereg3;  // ufix1 [8]
  reg [2:0] idxpipereg3;  // ufix3
  wire dec13_0;  // ufix1
  wire dec13_1;  // ufix1
  wire dec13_2;  // ufix1
  wire dec13_3;  // ufix1
  wire dec13_4;  // ufix1
  wire dec13_5;  // ufix1
  wire dec13_6;  // ufix1
  wire dec13_7;  // ufix1
  wire [2:0] idx13;  // ufix3
  wire dec14_0;  // ufix1
  wire dec14_1;  // ufix1
  wire dec14_2;  // ufix1
  wire dec14_3;  // ufix1
  wire dec14_4;  // ufix1
  wire dec14_5;  // ufix1
  wire dec14_6;  // ufix1
  wire dec14_7;  // ufix1
  wire [2:0] idx14;  // ufix3
  wire dec15_0;  // ufix1
  wire dec15_1;  // ufix1
  wire dec15_2;  // ufix1
  wire dec15_3;  // ufix1
  wire dec15_4;  // ufix1
  wire dec15_5;  // ufix1
  wire dec15_6;  // ufix1
  wire dec15_7;  // ufix1
  wire [2:0] idx15;  // ufix3
  wire dec16deadOut_0;  // ufix1
  wire dec16deadOut_1;  // ufix1
  wire dec16deadOut_2;  // ufix1
  wire dec16deadOut_3;  // ufix1
  wire dec16deadOut_4;  // ufix1
  wire dec16deadOut_5;  // ufix1
  wire dec16deadOut_6;  // ufix1
  wire dec16deadOut_7;  // ufix1
  wire [2:0] idx16;  // ufix3
  reg [2:0] idxpipereg4;  // ufix3


  // Traceback Component1
  TracebackUnit u_TracebackComp_inst1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec_0),  // ufix1
                                       .dec_in_1(dec_1),  // ufix1
                                       .dec_in_2(dec_2),  // ufix1
                                       .dec_in_3(dec_3),  // ufix1
                                       .dec_in_4(dec_4),  // ufix1
                                       .dec_in_5(dec_5),  // ufix1
                                       .dec_in_6(dec_6),  // ufix1
                                       .dec_in_7(dec_7),  // ufix1
                                       .idx_in(idx),  // ufix3
                                       .dec_out_0(dec1_0),  // ufix1
                                       .dec_out_1(dec1_1),  // ufix1
                                       .dec_out_2(dec1_2),  // ufix1
                                       .dec_out_3(dec1_3),  // ufix1
                                       .dec_out_4(dec1_4),  // ufix1
                                       .dec_out_5(dec1_5),  // ufix1
                                       .dec_out_6(dec1_6),  // ufix1
                                       .dec_out_7(dec1_7),  // ufix1
                                       .idx_out(idx1)  // ufix3
                                       );

  // Traceback Component2
  TracebackUnit u_TracebackComp_inst2 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec1_0),  // ufix1
                                       .dec_in_1(dec1_1),  // ufix1
                                       .dec_in_2(dec1_2),  // ufix1
                                       .dec_in_3(dec1_3),  // ufix1
                                       .dec_in_4(dec1_4),  // ufix1
                                       .dec_in_5(dec1_5),  // ufix1
                                       .dec_in_6(dec1_6),  // ufix1
                                       .dec_in_7(dec1_7),  // ufix1
                                       .idx_in(idx1),  // ufix3
                                       .dec_out_0(dec2_0),  // ufix1
                                       .dec_out_1(dec2_1),  // ufix1
                                       .dec_out_2(dec2_2),  // ufix1
                                       .dec_out_3(dec2_3),  // ufix1
                                       .dec_out_4(dec2_4),  // ufix1
                                       .dec_out_5(dec2_5),  // ufix1
                                       .dec_out_6(dec2_6),  // ufix1
                                       .dec_out_7(dec2_7),  // ufix1
                                       .idx_out(idx2)  // ufix3
                                       );

  // Traceback Component3
  TracebackUnit u_TracebackComp_inst3 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec2_0),  // ufix1
                                       .dec_in_1(dec2_1),  // ufix1
                                       .dec_in_2(dec2_2),  // ufix1
                                       .dec_in_3(dec2_3),  // ufix1
                                       .dec_in_4(dec2_4),  // ufix1
                                       .dec_in_5(dec2_5),  // ufix1
                                       .dec_in_6(dec2_6),  // ufix1
                                       .dec_in_7(dec2_7),  // ufix1
                                       .idx_in(idx2),  // ufix3
                                       .dec_out_0(dec3_0),  // ufix1
                                       .dec_out_1(dec3_1),  // ufix1
                                       .dec_out_2(dec3_2),  // ufix1
                                       .dec_out_3(dec3_3),  // ufix1
                                       .dec_out_4(dec3_4),  // ufix1
                                       .dec_out_5(dec3_5),  // ufix1
                                       .dec_out_6(dec3_6),  // ufix1
                                       .dec_out_7(dec3_7),  // ufix1
                                       .idx_out(idx3)  // ufix3
                                       );

  // Traceback Component4
  TracebackUnit u_TracebackComp_inst4 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec3_0),  // ufix1
                                       .dec_in_1(dec3_1),  // ufix1
                                       .dec_in_2(dec3_2),  // ufix1
                                       .dec_in_3(dec3_3),  // ufix1
                                       .dec_in_4(dec3_4),  // ufix1
                                       .dec_in_5(dec3_5),  // ufix1
                                       .dec_in_6(dec3_6),  // ufix1
                                       .dec_in_7(dec3_7),  // ufix1
                                       .idx_in(idx3),  // ufix3
                                       .dec_out_0(dec4_0),  // ufix1
                                       .dec_out_1(dec4_1),  // ufix1
                                       .dec_out_2(dec4_2),  // ufix1
                                       .dec_out_3(dec4_3),  // ufix1
                                       .dec_out_4(dec4_4),  // ufix1
                                       .dec_out_5(dec4_5),  // ufix1
                                       .dec_out_6(dec4_6),  // ufix1
                                       .dec_out_7(dec4_7),  // ufix1
                                       .idx_out(idx4)  // ufix3
                                       );

  assign dec4[0] = dec4_0;
  assign dec4[1] = dec4_1;
  assign dec4[2] = dec4_2;
  assign dec4[3] = dec4_3;
  assign dec4[4] = dec4_4;
  assign dec4[5] = dec4_5;
  assign dec4[6] = dec4_6;
  assign dec4[7] = dec4_7;

  // Decision pipeline register1
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_process
      if (reset == 1'b1) begin
        decpipereg1 <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg1 <= dec4;
        end
      end
    end



  // Index pipeline register1
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_process
      if (reset == 1'b1) begin
        idxpipereg1 <= 3'b000;
      end
      else begin
        if (enb) begin
          idxpipereg1 <= idx4;
        end
      end
    end



  // Traceback Component5
  TracebackUnit u_TracebackComp_inst5 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(decpipereg1[0]),  // ufix1
                                       .dec_in_1(decpipereg1[1]),  // ufix1
                                       .dec_in_2(decpipereg1[2]),  // ufix1
                                       .dec_in_3(decpipereg1[3]),  // ufix1
                                       .dec_in_4(decpipereg1[4]),  // ufix1
                                       .dec_in_5(decpipereg1[5]),  // ufix1
                                       .dec_in_6(decpipereg1[6]),  // ufix1
                                       .dec_in_7(decpipereg1[7]),  // ufix1
                                       .idx_in(idxpipereg1),  // ufix3
                                       .dec_out_0(dec5_0),  // ufix1
                                       .dec_out_1(dec5_1),  // ufix1
                                       .dec_out_2(dec5_2),  // ufix1
                                       .dec_out_3(dec5_3),  // ufix1
                                       .dec_out_4(dec5_4),  // ufix1
                                       .dec_out_5(dec5_5),  // ufix1
                                       .dec_out_6(dec5_6),  // ufix1
                                       .dec_out_7(dec5_7),  // ufix1
                                       .idx_out(idx5)  // ufix3
                                       );

  // Traceback Component6
  TracebackUnit u_TracebackComp_inst6 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec5_0),  // ufix1
                                       .dec_in_1(dec5_1),  // ufix1
                                       .dec_in_2(dec5_2),  // ufix1
                                       .dec_in_3(dec5_3),  // ufix1
                                       .dec_in_4(dec5_4),  // ufix1
                                       .dec_in_5(dec5_5),  // ufix1
                                       .dec_in_6(dec5_6),  // ufix1
                                       .dec_in_7(dec5_7),  // ufix1
                                       .idx_in(idx5),  // ufix3
                                       .dec_out_0(dec6_0),  // ufix1
                                       .dec_out_1(dec6_1),  // ufix1
                                       .dec_out_2(dec6_2),  // ufix1
                                       .dec_out_3(dec6_3),  // ufix1
                                       .dec_out_4(dec6_4),  // ufix1
                                       .dec_out_5(dec6_5),  // ufix1
                                       .dec_out_6(dec6_6),  // ufix1
                                       .dec_out_7(dec6_7),  // ufix1
                                       .idx_out(idx6)  // ufix3
                                       );

  // Traceback Component7
  TracebackUnit u_TracebackComp_inst7 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec6_0),  // ufix1
                                       .dec_in_1(dec6_1),  // ufix1
                                       .dec_in_2(dec6_2),  // ufix1
                                       .dec_in_3(dec6_3),  // ufix1
                                       .dec_in_4(dec6_4),  // ufix1
                                       .dec_in_5(dec6_5),  // ufix1
                                       .dec_in_6(dec6_6),  // ufix1
                                       .dec_in_7(dec6_7),  // ufix1
                                       .idx_in(idx6),  // ufix3
                                       .dec_out_0(dec7_0),  // ufix1
                                       .dec_out_1(dec7_1),  // ufix1
                                       .dec_out_2(dec7_2),  // ufix1
                                       .dec_out_3(dec7_3),  // ufix1
                                       .dec_out_4(dec7_4),  // ufix1
                                       .dec_out_5(dec7_5),  // ufix1
                                       .dec_out_6(dec7_6),  // ufix1
                                       .dec_out_7(dec7_7),  // ufix1
                                       .idx_out(idx7)  // ufix3
                                       );

  // Traceback Component8
  TracebackUnit u_TracebackComp_inst8 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(dec7_0),  // ufix1
                                       .dec_in_1(dec7_1),  // ufix1
                                       .dec_in_2(dec7_2),  // ufix1
                                       .dec_in_3(dec7_3),  // ufix1
                                       .dec_in_4(dec7_4),  // ufix1
                                       .dec_in_5(dec7_5),  // ufix1
                                       .dec_in_6(dec7_6),  // ufix1
                                       .dec_in_7(dec7_7),  // ufix1
                                       .idx_in(idx7),  // ufix3
                                       .dec_out_0(dec8_0),  // ufix1
                                       .dec_out_1(dec8_1),  // ufix1
                                       .dec_out_2(dec8_2),  // ufix1
                                       .dec_out_3(dec8_3),  // ufix1
                                       .dec_out_4(dec8_4),  // ufix1
                                       .dec_out_5(dec8_5),  // ufix1
                                       .dec_out_6(dec8_6),  // ufix1
                                       .dec_out_7(dec8_7),  // ufix1
                                       .idx_out(idx8)  // ufix3
                                       );

  assign dec8[0] = dec8_0;
  assign dec8[1] = dec8_1;
  assign dec8[2] = dec8_2;
  assign dec8[3] = dec8_3;
  assign dec8[4] = dec8_4;
  assign dec8[5] = dec8_5;
  assign dec8[6] = dec8_6;
  assign dec8[7] = dec8_7;

  // Decision pipeline register2
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_1_process
      if (reset == 1'b1) begin
        decpipereg2 <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg2 <= dec8;
        end
      end
    end



  // Index pipeline register2
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_1_process
      if (reset == 1'b1) begin
        idxpipereg2 <= 3'b000;
      end
      else begin
        if (enb) begin
          idxpipereg2 <= idx8;
        end
      end
    end



  // Traceback Component9
  TracebackUnit u_TracebackComp_inst9 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .dec_in_0(decpipereg2[0]),  // ufix1
                                       .dec_in_1(decpipereg2[1]),  // ufix1
                                       .dec_in_2(decpipereg2[2]),  // ufix1
                                       .dec_in_3(decpipereg2[3]),  // ufix1
                                       .dec_in_4(decpipereg2[4]),  // ufix1
                                       .dec_in_5(decpipereg2[5]),  // ufix1
                                       .dec_in_6(decpipereg2[6]),  // ufix1
                                       .dec_in_7(decpipereg2[7]),  // ufix1
                                       .idx_in(idxpipereg2),  // ufix3
                                       .dec_out_0(dec9_0),  // ufix1
                                       .dec_out_1(dec9_1),  // ufix1
                                       .dec_out_2(dec9_2),  // ufix1
                                       .dec_out_3(dec9_3),  // ufix1
                                       .dec_out_4(dec9_4),  // ufix1
                                       .dec_out_5(dec9_5),  // ufix1
                                       .dec_out_6(dec9_6),  // ufix1
                                       .dec_out_7(dec9_7),  // ufix1
                                       .idx_out(idx9)  // ufix3
                                       );

  // Traceback Component10
  TracebackUnit u_TracebackComp_inst10 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec9_0),  // ufix1
                                        .dec_in_1(dec9_1),  // ufix1
                                        .dec_in_2(dec9_2),  // ufix1
                                        .dec_in_3(dec9_3),  // ufix1
                                        .dec_in_4(dec9_4),  // ufix1
                                        .dec_in_5(dec9_5),  // ufix1
                                        .dec_in_6(dec9_6),  // ufix1
                                        .dec_in_7(dec9_7),  // ufix1
                                        .idx_in(idx9),  // ufix3
                                        .dec_out_0(dec10_0),  // ufix1
                                        .dec_out_1(dec10_1),  // ufix1
                                        .dec_out_2(dec10_2),  // ufix1
                                        .dec_out_3(dec10_3),  // ufix1
                                        .dec_out_4(dec10_4),  // ufix1
                                        .dec_out_5(dec10_5),  // ufix1
                                        .dec_out_6(dec10_6),  // ufix1
                                        .dec_out_7(dec10_7),  // ufix1
                                        .idx_out(idx10)  // ufix3
                                        );

  // Traceback Component11
  TracebackUnit u_TracebackComp_inst11 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec10_0),  // ufix1
                                        .dec_in_1(dec10_1),  // ufix1
                                        .dec_in_2(dec10_2),  // ufix1
                                        .dec_in_3(dec10_3),  // ufix1
                                        .dec_in_4(dec10_4),  // ufix1
                                        .dec_in_5(dec10_5),  // ufix1
                                        .dec_in_6(dec10_6),  // ufix1
                                        .dec_in_7(dec10_7),  // ufix1
                                        .idx_in(idx10),  // ufix3
                                        .dec_out_0(dec11_0),  // ufix1
                                        .dec_out_1(dec11_1),  // ufix1
                                        .dec_out_2(dec11_2),  // ufix1
                                        .dec_out_3(dec11_3),  // ufix1
                                        .dec_out_4(dec11_4),  // ufix1
                                        .dec_out_5(dec11_5),  // ufix1
                                        .dec_out_6(dec11_6),  // ufix1
                                        .dec_out_7(dec11_7),  // ufix1
                                        .idx_out(idx11)  // ufix3
                                        );

  // Traceback Component12
  TracebackUnit u_TracebackComp_inst12 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec11_0),  // ufix1
                                        .dec_in_1(dec11_1),  // ufix1
                                        .dec_in_2(dec11_2),  // ufix1
                                        .dec_in_3(dec11_3),  // ufix1
                                        .dec_in_4(dec11_4),  // ufix1
                                        .dec_in_5(dec11_5),  // ufix1
                                        .dec_in_6(dec11_6),  // ufix1
                                        .dec_in_7(dec11_7),  // ufix1
                                        .idx_in(idx11),  // ufix3
                                        .dec_out_0(dec12_0),  // ufix1
                                        .dec_out_1(dec12_1),  // ufix1
                                        .dec_out_2(dec12_2),  // ufix1
                                        .dec_out_3(dec12_3),  // ufix1
                                        .dec_out_4(dec12_4),  // ufix1
                                        .dec_out_5(dec12_5),  // ufix1
                                        .dec_out_6(dec12_6),  // ufix1
                                        .dec_out_7(dec12_7),  // ufix1
                                        .idx_out(idx12)  // ufix3
                                        );

  assign dec12[0] = dec12_0;
  assign dec12[1] = dec12_1;
  assign dec12[2] = dec12_2;
  assign dec12[3] = dec12_3;
  assign dec12[4] = dec12_4;
  assign dec12[5] = dec12_5;
  assign dec12[6] = dec12_6;
  assign dec12[7] = dec12_7;

  // Decision pipeline register3
  always @(posedge clk or posedge reset)
    begin : decpipelineregister_2_process
      if (reset == 1'b1) begin
        decpipereg3 <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          decpipereg3 <= dec12;
        end
      end
    end



  // Index pipeline register3
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_2_process
      if (reset == 1'b1) begin
        idxpipereg3 <= 3'b000;
      end
      else begin
        if (enb) begin
          idxpipereg3 <= idx12;
        end
      end
    end



  // Traceback Component13
  TracebackUnit u_TracebackComp_inst13 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(decpipereg3[0]),  // ufix1
                                        .dec_in_1(decpipereg3[1]),  // ufix1
                                        .dec_in_2(decpipereg3[2]),  // ufix1
                                        .dec_in_3(decpipereg3[3]),  // ufix1
                                        .dec_in_4(decpipereg3[4]),  // ufix1
                                        .dec_in_5(decpipereg3[5]),  // ufix1
                                        .dec_in_6(decpipereg3[6]),  // ufix1
                                        .dec_in_7(decpipereg3[7]),  // ufix1
                                        .idx_in(idxpipereg3),  // ufix3
                                        .dec_out_0(dec13_0),  // ufix1
                                        .dec_out_1(dec13_1),  // ufix1
                                        .dec_out_2(dec13_2),  // ufix1
                                        .dec_out_3(dec13_3),  // ufix1
                                        .dec_out_4(dec13_4),  // ufix1
                                        .dec_out_5(dec13_5),  // ufix1
                                        .dec_out_6(dec13_6),  // ufix1
                                        .dec_out_7(dec13_7),  // ufix1
                                        .idx_out(idx13)  // ufix3
                                        );

  // Traceback Component14
  TracebackUnit u_TracebackComp_inst14 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec13_0),  // ufix1
                                        .dec_in_1(dec13_1),  // ufix1
                                        .dec_in_2(dec13_2),  // ufix1
                                        .dec_in_3(dec13_3),  // ufix1
                                        .dec_in_4(dec13_4),  // ufix1
                                        .dec_in_5(dec13_5),  // ufix1
                                        .dec_in_6(dec13_6),  // ufix1
                                        .dec_in_7(dec13_7),  // ufix1
                                        .idx_in(idx13),  // ufix3
                                        .dec_out_0(dec14_0),  // ufix1
                                        .dec_out_1(dec14_1),  // ufix1
                                        .dec_out_2(dec14_2),  // ufix1
                                        .dec_out_3(dec14_3),  // ufix1
                                        .dec_out_4(dec14_4),  // ufix1
                                        .dec_out_5(dec14_5),  // ufix1
                                        .dec_out_6(dec14_6),  // ufix1
                                        .dec_out_7(dec14_7),  // ufix1
                                        .idx_out(idx14)  // ufix3
                                        );

  // Traceback Component15
  TracebackUnit u_TracebackComp_inst15 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec14_0),  // ufix1
                                        .dec_in_1(dec14_1),  // ufix1
                                        .dec_in_2(dec14_2),  // ufix1
                                        .dec_in_3(dec14_3),  // ufix1
                                        .dec_in_4(dec14_4),  // ufix1
                                        .dec_in_5(dec14_5),  // ufix1
                                        .dec_in_6(dec14_6),  // ufix1
                                        .dec_in_7(dec14_7),  // ufix1
                                        .idx_in(idx14),  // ufix3
                                        .dec_out_0(dec15_0),  // ufix1
                                        .dec_out_1(dec15_1),  // ufix1
                                        .dec_out_2(dec15_2),  // ufix1
                                        .dec_out_3(dec15_3),  // ufix1
                                        .dec_out_4(dec15_4),  // ufix1
                                        .dec_out_5(dec15_5),  // ufix1
                                        .dec_out_6(dec15_6),  // ufix1
                                        .dec_out_7(dec15_7),  // ufix1
                                        .idx_out(idx15)  // ufix3
                                        );

  // Traceback Component16
  // Decision pipeline register4
  TracebackUnit u_TracebackComp_inst16 (.clk(clk),
                                        .reset(reset),
                                        .enb(enb),
                                        .dec_in_0(dec15_0),  // ufix1
                                        .dec_in_1(dec15_1),  // ufix1
                                        .dec_in_2(dec15_2),  // ufix1
                                        .dec_in_3(dec15_3),  // ufix1
                                        .dec_in_4(dec15_4),  // ufix1
                                        .dec_in_5(dec15_5),  // ufix1
                                        .dec_in_6(dec15_6),  // ufix1
                                        .dec_in_7(dec15_7),  // ufix1
                                        .idx_in(idx15),  // ufix3
                                        .dec_out_0(dec16deadOut_0),  // ufix1
                                        .dec_out_1(dec16deadOut_1),  // ufix1
                                        .dec_out_2(dec16deadOut_2),  // ufix1
                                        .dec_out_3(dec16deadOut_3),  // ufix1
                                        .dec_out_4(dec16deadOut_4),  // ufix1
                                        .dec_out_5(dec16deadOut_5),  // ufix1
                                        .dec_out_6(dec16deadOut_6),  // ufix1
                                        .dec_out_7(dec16deadOut_7),  // ufix1
                                        .idx_out(idx16)  // ufix3
                                        );

  // Index pipeline register4
  always @(posedge clk or posedge reset)
    begin : idxpipelineregister_3_process
      if (reset == 1'b1) begin
        idxpipereg4 <= 3'b000;
      end
      else begin
        if (enb) begin
          idxpipereg4 <= idx16;
        end
      end
    end



  assign decoded = idxpipereg4[2];



endmodule  // Traceback

