// -------------------------------------------------------------
// 
// File Name: hdlsrc\gm_hdlcoder_commviterbi\TracebackUnit.v
// Created: 2024-06-18 17:16:01
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TracebackUnit
// Source Path: gm_hdlcoder_commviterbi/Viterbi Decoder Subsystem/Viterbi Decoder1/Traceback/TracebackUnit
// Hierarchy Level: 3
// Model version: 10.6
// 
// Traceback Decoding Unit
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TracebackUnit
          (clk,
           reset,
           enb,
           dec_in_0,
           dec_in_1,
           dec_in_2,
           dec_in_3,
           dec_in_4,
           dec_in_5,
           dec_in_6,
           dec_in_7,
           idx_in,
           dec_out_0,
           dec_out_1,
           dec_out_2,
           dec_out_3,
           dec_out_4,
           dec_out_5,
           dec_out_6,
           dec_out_7,
           idx_out);


  input   clk;
  input   reset;
  input   enb;
  input   dec_in_0;  // ufix1
  input   dec_in_1;  // ufix1
  input   dec_in_2;  // ufix1
  input   dec_in_3;  // ufix1
  input   dec_in_4;  // ufix1
  input   dec_in_5;  // ufix1
  input   dec_in_6;  // ufix1
  input   dec_in_7;  // ufix1
  input   [2:0] idx_in;  // ufix3
  output  dec_out_0;  // ufix1
  output  dec_out_1;  // ufix1
  output  dec_out_2;  // ufix1
  output  dec_out_3;  // ufix1
  output  dec_out_4;  // ufix1
  output  dec_out_5;  // ufix1
  output  dec_out_6;  // ufix1
  output  dec_out_7;  // ufix1
  output  [2:0] idx_out;  // ufix3


  wire [7:0] dec_in;  // ufix1 [8]
  reg  [7:0] dec_out;  // ufix1 [8]
  wire [1:0] slicedidx;  // ufix2
  wire thread;  // ufix1


  assign dec_in[0] = dec_in_0;
  assign dec_in[1] = dec_in_1;
  assign dec_in[2] = dec_in_2;
  assign dec_in[3] = dec_in_3;
  assign dec_in[4] = dec_in_4;
  assign dec_in[5] = dec_in_5;
  assign dec_in[6] = dec_in_6;
  assign dec_in[7] = dec_in_7;

  always @(posedge clk or posedge reset)
    begin : decshiftRegister_process
      if (reset == 1'b1) begin
        dec_out <= {8{1'b0}};
      end
      else begin
        if (enb) begin
          dec_out <= dec_in;
        end
      end
    end



  assign dec_out_0 = dec_out[0];

  assign dec_out_1 = dec_out[1];

  assign dec_out_2 = dec_out[2];

  assign dec_out_3 = dec_out[3];

  assign dec_out_4 = dec_out[4];

  assign dec_out_5 = dec_out[5];

  assign dec_out_6 = dec_out[6];

  assign dec_out_7 = dec_out[7];

  assign slicedidx = idx_in[1:0];



  // Decode the previous state based on current state and the decision branch
  assign thread = (idx_in == 3'b000 ? dec_in[0] :
              (idx_in == 3'b001 ? dec_in[1] :
              (idx_in == 3'b010 ? dec_in[2] :
              (idx_in == 3'b011 ? dec_in[3] :
              (idx_in == 3'b100 ? dec_in[4] :
              (idx_in == 3'b101 ? dec_in[5] :
              (idx_in == 3'b110 ? dec_in[6] :
              dec_in[7])))))));



  assign idx_out = {slicedidx, thread};



endmodule  // TracebackUnit

